// Code generated by go-swagger; DO NOT EDIT.

// Package restapi fio-stats
//
//  Provides information about FIO https://fioprotocol.io
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
