// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSuggestSetfeemultHandlerFunc turns a function with the right signature into a get suggest setfeemult handler
type GetSuggestSetfeemultHandlerFunc func(GetSuggestSetfeemultParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSuggestSetfeemultHandlerFunc) Handle(params GetSuggestSetfeemultParams) middleware.Responder {
	return fn(params)
}

// GetSuggestSetfeemultHandler interface for that can handle valid get suggest setfeemult params
type GetSuggestSetfeemultHandler interface {
	Handle(GetSuggestSetfeemultParams) middleware.Responder
}

// NewGetSuggestSetfeemult creates a new http.Handler for the get suggest setfeemult operation
func NewGetSuggestSetfeemult(ctx *middleware.Context, handler GetSuggestSetfeemultHandler) *GetSuggestSetfeemult {
	return &GetSuggestSetfeemult{Context: ctx, Handler: handler}
}

/* GetSuggestSetfeemult swagger:route GET /suggest/setfeemult getSuggestSetfeemult

A suggested fee multipler as used for fio.fee::setfeemult, based on a target price for the 'register_fio_address' endpoint AND the output from the /suggest/feevote endpoint

*/
type GetSuggestSetfeemult struct {
	Context *middleware.Context
	Handler GetSuggestSetfeemultHandler
}

func (o *GetSuggestSetfeemult) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSuggestSetfeemultParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetSuggestSetfeemultOKBody get suggest setfeemult o k body
//
// swagger:model GetSuggestSetfeemultOKBody
type GetSuggestSetfeemultOKBody struct {

	// suggested multiplier
	SuggestedMultiplier float64 `json:"suggested_multiplier,omitempty"`
}

// Validate validates this get suggest setfeemult o k body
func (o *GetSuggestSetfeemultOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get suggest setfeemult o k body based on context it is used
func (o *GetSuggestSetfeemultOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSuggestSetfeemultOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSuggestSetfeemultOKBody) UnmarshalBinary(b []byte) error {
	var res GetSuggestSetfeemultOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
