// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/blockpane/fio-web-utils/stats-api/models"
)

// GetSuggestFeevoteOKCode is the HTTP code returned for type GetSuggestFeevoteOK
const GetSuggestFeevoteOKCode int = 200

/*GetSuggestFeevoteOK array of fio.fee feevalue

swagger:response getSuggestFeevoteOK
*/
type GetSuggestFeevoteOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Feevote `json:"body,omitempty"`
}

// NewGetSuggestFeevoteOK creates GetSuggestFeevoteOK with default headers values
func NewGetSuggestFeevoteOK() *GetSuggestFeevoteOK {

	return &GetSuggestFeevoteOK{}
}

// WithPayload adds the payload to the get suggest feevote o k response
func (o *GetSuggestFeevoteOK) WithPayload(payload []*models.Feevote) *GetSuggestFeevoteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get suggest feevote o k response
func (o *GetSuggestFeevoteOK) SetPayload(payload []*models.Feevote) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSuggestFeevoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Feevote, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
