// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFeeMultiplierProducerHandlerFunc turns a function with the right signature into a get fee multiplier producer handler
type GetFeeMultiplierProducerHandlerFunc func(GetFeeMultiplierProducerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeeMultiplierProducerHandlerFunc) Handle(params GetFeeMultiplierProducerParams) middleware.Responder {
	return fn(params)
}

// GetFeeMultiplierProducerHandler interface for that can handle valid get fee multiplier producer params
type GetFeeMultiplierProducerHandler interface {
	Handle(GetFeeMultiplierProducerParams) middleware.Responder
}

// NewGetFeeMultiplierProducer creates a new http.Handler for the get fee multiplier producer operation
func NewGetFeeMultiplierProducer(ctx *middleware.Context, handler GetFeeMultiplierProducerHandler) *GetFeeMultiplierProducer {
	return &GetFeeMultiplierProducer{Context: ctx, Handler: handler}
}

/* GetFeeMultiplierProducer swagger:route GET /fee/multiplier/{producer} getFeeMultiplierProducer

list a producer's multiplier

*/
type GetFeeMultiplierProducer struct {
	Context *middleware.Context
	Handler GetFeeMultiplierProducerHandler
}

func (o *GetFeeMultiplierProducer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeeMultiplierProducerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetFeeMultiplierProducerOKBody get fee multiplier producer o k body
//
// swagger:model GetFeeMultiplierProducerOKBody
type GetFeeMultiplierProducerOKBody struct {

	// multiplier
	Multiplier float64 `json:"multiplier,omitempty"`

	// Unix timestap of when the fee vote was set
	Timestamp uint64 `json:"timestamp,omitempty"`
}

// Validate validates this get fee multiplier producer o k body
func (o *GetFeeMultiplierProducerOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get fee multiplier producer o k body based on context it is used
func (o *GetFeeMultiplierProducerOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFeeMultiplierProducerOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFeeMultiplierProducerOKBody) UnmarshalBinary(b []byte) error {
	var res GetFeeMultiplierProducerOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
